### ISSUE TITLE
can u make a phar pre release please

### ISSUE THREAD

**Issue by HyGlobalHD** [applqpak/HelpModifier#1]
i need it.

**Comment by applqpak** [comment]
Sorry for not seeing this until now. But you can download the ZIP then go over to http://pmt.mcpe.me and convert it into a PHAR.

**Comment by ifvictr** [comment]
@HyGlobalHD You can use the one I made awhile back, it doesn't need to be compiled to PHAR, just download and drop. https://github.com/NebulaLabs/PocketMine-Plugins/blob/master/Scripts/HelpTailor.php
