### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by ifvictr** [applqpak/HelpModifier#2]
The amount of code used in this plugin could be reduced significantly. You should utilize loops.

**Comment by applqpak** [comment]
Yeah, thanks!

**Comment by applqpak** [comment]
Do you mind doing that? This is an old project, and has been inactive for a bit now, lol.

**Comment by ifvictr** [comment]
@applqpak No need, I've made one here already awhile back: https://github.com/NebulaLabs/PocketMine-Plugins/blob/master/Scripts/HelpTailor.php You can learn a thing or two from it. :smile:

**Comment by applqpak** [comment]
Okay, thanks. :)
